apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  chart: fluent-bit
  repo: http://charts.cnrancher.cn/api/mqtt/charts
  targetNamespace: kube-system
  valuesContent: |-
   image:
     fluent_bit:
       repository: fluent/fluent-bit
       tag: 1.3.7
     pullPolicy: Always

   backend:
     type: forward
     forward:
       host: fluentd
       port: 24284
       tls: "off"
       tls_verify: "on"
       tls_debug: 1
       shared_key:
     es:
       host: elasticsearch
       port: 9200
       # Elastic Index Name
       index: kubernetes_cluster
       type: flb_type
       logstash_prefix: kubernetes_cluster
       replace_dots: "On"
       logstash_format: "On"
       retry_limit: "False"
       time_key: "@timestamp"
       # Optional username credential for Elastic X-Pack access
       http_user:
       # Password for user defined in HTTP_User
       http_passwd:
       # Optional TLS encryption to ElasticSearch instance
       tls: "off"
       tls_verify: "on"
       # TLS certificate for the Elastic (in PEM format). Use if tls=on and tls_verify=on.
       tls_ca: ""
       # TLS debugging levels = 1-4
       tls_debug: 1

   input:
     tail:
       memBufLimit: 5MB
       parser: docker
       path: /var/log/containers/*.log
       ignore_older: ""
       dockerMode: false
       dockerModeFlush: 4
    
    serviceAccount:
     # Specifies whether a ServiceAccount should be created
     create: true
     # Annotations to add to the service account
     annotations: {}
     # The name of the ServiceAccount to use.
     # If not set and create is true, a name is generated using the fullname template
     name:

    filter:
     kubeURL: https://kubernetes.default.svc:443
     kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
     kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
     kubeTag: kube
     kubeTagPrefix: kube.var.log.containers.

   resources: {}
     # limits:
     #   cpu: 100m
     #   memory: 128Mi
     # requests:
     #   cpu: 10m
     #   memory: 8Mi